interface ICar {
  img: string;
  brand: string;
  model: string;
  year: number;
  fuel: string;
  km: number;
  price: string;
  description: string;
  color: string;
  user: string;
}

export const cars: ICar[] = [
  {
    img: "https://cdn.motor1.com/images/mgl/3oN8A/s1/2022-audi-a4-renderings.jpg",
    brand: "Audi",
    model: "A4",
    year: 2021,
    fuel: "Gasolina",
    km: 1500,
    price: "175000.00",
    description:
      "O Audi A4 é um sedã médio de luxo alemão que possui um visual sofisticado e elegante, com um motor potente e muita tecnologia embarcada.",
    user: "Lucas Silva",
    color: "Branco",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/XBB6wV/s1/2022-bmw-3er-limousine.jpg",
    brand: "BMW",
    model: "Série 3",
    year: 2022,
    fuel: "Etanol",
    km: 800,
    price: "185000.00",
    description:
      "O BMW Série 3 é um sedã médio de luxo alemão que oferece desempenho esportivo, conforto e elegância, além de uma ampla variedade de opções de personalização.",
    user: "Maria Souza",
    color: "Preto",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/lEEKbW/s3/chevrolet-camaro-ss-2022.jpg",
    brand: "Chevrolet",
    model: "Camaro",
    year: 2020,
    fuel: "Gasolina",
    km: 5000,
    price: "375000.00",
    description:
      "O Chevrolet Camaro é um cupê esportivo americano que possui um design icônico e um motor potente, sendo uma escolha popular entre os entusiastas de carros esportivos.",
    user: "Pedro Oliveira",
    color: "Amarelo",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/xNxMP/s3/2022-dodge-challenger-hemi-orange-and-srt-black-packages.jpg",
    brand: "Dodge",
    model: "Challenger",
    year: 2021,
    fuel: "Gasolina",
    km: 3000,
    price: "390000.00",
    description:
      "O Dodge Challenger é um cupê esportivo americano que oferece desempenho impressionante, estilo retrô e uma variedade de opções de personalização, tornando-o uma escolha popular entre os fãs de muscle cars.",
    user: "Paulo Coelho",
    color: "Vermelho",
  },
  {
    img: "https://s2.glbimg.com/OxQCUxDFzYWtGWpyP527JmYTrDM=/0x0:1600x900/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2021/u/b/0wAdVbSYGDoEApEglDwg/ferrari-portofinom-2.jpg",
    brand: "Ferrari",
    model: "Portofino",
    year: 2019,
    fuel: "Gasolina",
    km: 12000,
    price: "2500000.00",
    description:
      "A Ferrari Portofino é um conversível de luxo italiano que combina elegância e desempenho, com um motor V8 turbocharged de 600 cavalos de potência e um design aerodinâmico e sofisticado.",
    user: "Camila Rodrigues",
    color: "Vermelho",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/1xqZM/s1/4x3/mustang-mach-1.webp",
    brand: "Ford",
    model: "Mustang",
    year: 2020,
    fuel: "Gasolina",
    km: 2000,
    price: "325000.00",
    description:
      "O Ford Mustang é um cupê esportivo americano que possui um design clássico e um motor potente, sendo uma escolha popular entre os entusiastas de carros esportivos.",
    user: "Gustavo Silva",
    color: "Azul",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/3K0OL/s1/honda-civic-prototype-2022.webp",
    brand: "Honda",
    model: "Civic",
    year: 2018,
    fuel: "Etanol",
    km: 35000,
    price: "120000.00",
    description:
      "O Honda Civic é um sedan compacto japonês que oferece desempenho, confiabilidade e economia de combustível, sendo uma escolha popular entre os motoristas que buscam um carro econômico e eficiente.",
    user: "Julia Santos",
    color: "Cinza",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/y22ALG/s1/jaguar-f-type-cabrio-p300.webp",
    brand: "Jaguar",
    model: "F-Type",
    year: 2017,
    fuel: "Gasolina",
    km: 45000,
    price: "425000.00",
    description:
      "O Jaguar F-Type é um cupê esportivo britânico que combina luxo e desempenho, com um design elegante e um motor potente, tornando-o uma escolha popular entre os motoristas que procuram um carro de alto desempenho e estilo.",
    user: "Rafael Oliveira",
    color: "Branco",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/2VMZM/s1/4x3/2018-kia-stinger-gt-first-drive.webp",
    brand: "Kia",
    model: "Stinger",
    year: 2022,
    fuel: "Gasolina",
    km: 500,
    price: "210000.00",
    description:
      "O Kia Stinger é um sedan de luxo sul-coreano que oferece desempenho, estilo e conforto, sendo uma escolha popular entre os motoristas que buscam um carro sofisticado e elegante.",
    user: "Fernanda Costa",
    color: "Preto",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/4JyZA/s1/4x3/lamborghini-aventador-lp-780-4-ultimae.webp",
    brand: "Lamborghini",
    model: "Aventador",
    year: 2022,
    fuel: "Gasolina",
    km: 100,
    price: "5500000.00",
    description:
      "O Lamborghini Aventador é um supercarro italiano que combina design futurista, desempenho impressionante e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro de alto desempenho e estilo.",
    user: "Giovanna Pereira",
    color: "Amarelo",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/VAZGy/s3/2022-mercedes-amg-gt-4-door-exterior.jpg",
    brand: "Mercedes-Benz",
    model: "AMG GT",
    year: 2021,
    fuel: "Gasolina",
    km: 8000,
    price: "500000.00",
    description:
      "O Mercedes-Benz AMG GT é um cupê esportivo alemão que combina desempenho e elegância, com um motor potente e um design sofisticado e aerodinâmico.",
    user: "Luiz Carlos",
    color: "Prata",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/g4A1e8/s3/2024-nissan-gt-r-nismo-special-edition.jpg",
    brand: "Nissan",
    model: "GT-R",
    year: 2020,
    fuel: "Gasolina",
    km: 1500,
    price: "600000.00",
    description:
      "O Nissan GT-R é um supercarro japonês que oferece desempenho impressionante, estilo esportivo e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro de alto desempenho.",
    user: "André Rodrigues",
    color: "Vermelho",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/ZnKvO2/s1/2023-porsche-911-carrera-t-in-gulf-blue.jpg",
    brand: "Porsche",
    model: "911",
    year: 2019,
    fuel: "Gasolina",
    km: 18000,
    price: "700000.00",
    description:
      "O Porsche 911 é um cupê esportivo alemão que combina desempenho, estilo e sofisticação, com um motor potente e uma ampla variedade de opções de personalização.",
    user: "Ana Maria",
    color: "Azul",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/no476/s1/tesla-model-s-ja-esta-sendo-vendido-no-brasil-por-r-650-mil1.webp",
    brand: "Tesla",
    model: "Model S",
    year: 2022,
    fuel: "Elétrico",
    km: 50,
    price: "800000.00",
    description:
      "O Tesla Model S é um sedan elétrico americano que oferece desempenho, tecnologia avançada e uma autonomia impressionante, tornando-o uma escolha popular entre os motoristas que procuram um carro elétrico de alto desempenho.",
    user: "Rodrigo Nunes",
    color: "Branco",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/nAAZlR/s1/2022-toyota-supra.jpg",
    brand: "Toyota",
    model: "Supra",
    year: 2021,
    fuel: "Gasolina",
    km: 500,
    price: "350000.00",
    description:
      "O Toyota Supra é um cupê esportivo japonês que combina desempenho, estilo e tecnologia, com um motor potente e um design aerodinâmico e moderno.",
    user: "Amanda Souza",
    color: "Preto",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/7R6aJ/s1/2022-volkswagen-golf-gti.jpg",
    brand: "Volkswagen",
    model: "Golf GTI",
    year: 2018,
    fuel: "Gasolina",
    km: 40000,
    price: "120000.00",
    description:
      "O Volkswagen Golf GTI é um hatchback esportivo alemão que combina desempenho, praticidade e tecnologia, sendo uma escolha popular entre os motoristas que procuram um carro esportivo versátil e funcional.",
    user: "Roberto Santos",
    color: "Vermelho",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/1zLkG/s1/2022-lexus-lc-500-convertible.jpg",
    brand: "Lexus",
    model: "LC 500",
    year: 2020,
    fuel: "Gasolina",
    km: 5000,
    price: "900000.00",
    description:
      "O Lexus LC 500 é um cupê de luxo japonês que combina design arrojado, conforto e desempenho, sendo uma escolha popular entre os motoristas que procuram um carro elegante e sofisticado.",
    user: "Carla Silva",
    color: "Branco",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/kRpwR/s1/2022-mclaren-artura.jpg",
    brand: "McLaren",
    model: "Artura",
    year: 2021,
    fuel: "Gasolina",
    km: 200,
    price: "3500000.00",
    description:
      "O McLaren Artura é um supercarro britânico que combina tecnologia híbrida, design futurista e desempenho impressionante, sendo uma escolha popular entre os motoristas que procuram um carro exclusivo e avançado.",
    user: "Felipe Santos",
    color: "Vermelho",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/XMplE/s1/2023-acura-nsx.jpg",
    brand: "Acura",
    model: "NSX",
    year: 2022,
    fuel: "Híbrido",
    km: 100,
    price: "1800000.00",
    description:
      "O Acura NSX é um supercarro híbrido japonês que combina design moderno, tecnologia avançada e desempenho excepcional, sendo uma escolha popular entre os motoristas que procuram um carro de alta performance e eficiência energética.",
    user: "Ricardo Silva",
    color: "Azul",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/mxqW8/s1/2022-mercedes-benz-s-class.jpg",
    brand: "Mercedes-Benz",
    model: "S-Class",
    year: 2021,
    fuel: "Gasolina",
    km: 1000,
    price: "1400000.00",
    description:
      "O Mercedes-Benz S-Class é um sedã de luxo alemão que combina design sofisticado, tecnologia avançada e conforto excepcional, sendo uma escolha popular entre os motoristas que procuram um carro de alta classe e qualidade.",
    user: "Mariana Oliveira",
    color: "Prata",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/nD2Qk/s1/2022-audi-e-tron-gt.jpg",
    brand: "Audi",
    model: "e-tron GT",
    year: 2022,
    fuel: "Elétrico",
    km: 100,
    price: "800000.00",
    description:
      "O Audi e-tron GT é um sedan elétrico de luxo que combina desempenho, design sofisticado e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro de alta performance e eficiência energética.",
    user: "Lucas Oliveira",
    color: "Azul",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/P5YP5/s1/2022-porsche-cayenne-coupe.jpg",
    brand: "Porsche",
    model: "Cayenne Coupé",
    year: 2020,
    fuel: "Gasolina",
    km: 12000,
    price: "650000.00",
    description:
      "O Porsche Cayenne Coupé é um SUV esportivo alemão que combina desempenho, design elegante e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro de alto desempenho e conforto.",
    user: "Thiago Santos",
    color: "Preto",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/3G2yj/s1/2022-land-rover-defender-v8.jpg",
    brand: "Land Rover",
    model: "Defender V8",
    year: 2021,
    fuel: "Gasolina",
    km: 500,
    price: "700000.00",
    description:
      "O Land Rover Defender V8 é um SUV britânico que combina desempenho off-road, design icônico e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro capaz de enfrentar qualquer terreno.",
    user: "Gabriel Silva",
    color: "Verde",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/3q3lo/s1/2022-tesla-model-x.jpg",
    brand: "Tesla",
    model: "Model X",
    year: 2022,
    fuel: "Elétrico",
    km: 200,
    price: "1000000.00",
    description:
      "O Tesla Model X é um SUV elétrico americano que oferece desempenho, tecnologia avançada e uma autonomia impressionante, tornando-o uma escolha popular entre os motoristas que procuram um carro elétrico de alto desempenho e luxo.",
    user: "Carla Santos",
    color: "Branco",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/9XKjE/s1/2022-jeep-wrangler-rubicon.jpg",
    brand: "Jeep",
    model: "Wrangler Rubicon",
    year: 2021,
    fuel: "Gasolina",
    km: 8000,
    price: "320000.00",
    description:
      "O Jeep Wrangler Rubicon é um SUV off-road americano que combina desempenho, estilo retrô e capacidade todo-terreno, sendo uma escolha popular entre os motoristas que procuram um carro capaz de enfrentar qualquer desafio.",
    user: "Marcelo Souza",
    color: "Vermelho",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/kEDKj/s1/2022-bmw-m5-cs.jpg",
    brand: "BMW",
    model: "M5 CS",
    year: 2021,
    fuel: "Gasolina",
    km: 1500,
    price: "1300000.00",
    description:
      "O BMW M5 CS é um sedan esportivo alemão que combina desempenho, design sofisticado e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro de alto desempenho e luxo.",
    user: "Fernando Alves",
    color: "Cinza",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/2QXVA/s1/2022-ford-f-150-raptor-r.jpg",
    brand: "Ford",
    model: "F-150 Raptor R",
    year: 2022,
    fuel: "Gasolina",
    km: 0,
    price: "700000.00",
    description:
      "O Ford F-150 Raptor R é uma picape de alto desempenho americana que combina capacidade off-road, design agressivo e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro robusto e poderoso.",
    user: "Rafaela Oliveira",
    color: "Laranja",
  },
  {
    img: "https://cdn.motor1.com/images/mgl/yJQ2n/s1/2022-aston-martin-vantage-f1-edition.jpg",
    brand: "Aston Martin",
    model: "Vantage F1 Edition",
    year: 2021,
    fuel: "Gasolina",
    km: 2000,
    price: "1700000.00",
    description:
      "O Aston Martin Vantage F1 Edition é um cupê esportivo britânico que combina desempenho, design sofisticado e tecnologia avançada, sendo uma escolha popular entre os motoristas que procuram um carro de alto desempenho e estilo.",
    user: "Renato Lima",
    color: "Vermelho",
  },
];
